name: rightClick
options:
  bundleIdPrefix: com.rightclick
  deploymentTarget:
    macOS: "12.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    DEVELOPMENT_TEAM: NXW23RM4GM

targets:
  rightClick:
    type: application
    platform: macOS
    sources:
      - path: rightClick
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rightclick.app
        INFOPLIST_FILE: rightClick/Info.plist
        CODE_SIGN_ENTITLEMENTS: rightClick/rightClick.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: FinderSyncExtension
        embed: true
        codeSign: true
        copyPhase:
          destination: plugins

  FinderSyncExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: FinderSyncExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rightclick.app.FinderSyncExtension
        INFOPLIST_FILE: FinderSyncExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: FinderSyncExtension/FinderSyncExtension.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/../Frameworks"
          - "@executable_path/../../../../Frameworks"
